# Generated by Django 5.0.2 on 2024-02-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crea', '0006_remove_empleado_email_remove_empleado_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad_disponible',
            name='proceso',
            field=models.CharField(choices=[('Proceso de Venta', 'Proceso de Venta'), ('Vendida', 'Vendida'), ('Jurídico', 'Jurídico')], max_length=20),
        ),
    ]
