# Generated by Django 5.0.2 on 2024-02-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crea', '0009_cliente_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_usuario', models.FileField(blank=True, upload_to='foto_usuario/')),
            ],
        ),
    ]
