# Generated by Django 5.0.2 on 2024-02-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crea', '0011_perfil_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad_posible',
            name='foto_propiedad',
            field=models.FileField(blank=True, upload_to='foto_propiedad/'),
        ),
    ]
