# Generated by Django 5.0.2 on 2024-02-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crea', '0020_rename_telefono_empleado_celular_empleado_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.CharField(choices=[('Aprovicionamiento', 'Aprovicionamiento'), ('Ventas', 'Ventas'), ('Tramites', 'Tramites')], max_length=50, null=True),
        ),
    ]
