# Generated by Django 5.0.2 on 2024-02-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crea', '0021_alter_empleado_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observaciones_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
