# Generated by Django 5.0.2 on 2024-02-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crea', '0022_cliente_observaciones_adicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='observaciones_adicionales',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
