# Generated by Django 5.0.2 on 2024-02-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crea', '0024_propiedad_disponible_proceso_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad_disponible',
            name='proceso_venta',
            field=models.CharField(choices=[('1', 'Levantamiento planimétrico de compra y venta (1 semana)'), ('2', 'Aprobación de la planimetría en el municipio (3 semanas)'), ('3', 'Minuta y documentación en notaria (4 días)'), ('4', 'Ingreso de la carpeta en notaria (3 días)'), ('5', 'Espera para la asignación de un perito evaluador (3 semanas)'), ('6', 'Aprobación de perito evaluador (3 días)'), ('7', 'Crédito aprobado'), ('8', 'Firmas de traspaso de dominio en notaria'), ('9', 'Registro del crédito hipotecario en el municipio(3 días)'), ('10', 'Fin'), ('11', 'Levantamiento planimétrico de compra y venta (1 semana)'), ('12', 'Aprobación de la planimetría en el municipio (3 semanas)'), ('13', 'Minuta y documentación en notaria (4 días)'), ('14', 'Ingreso al departamento de rentas en el municipio (1 semana)'), ('15', 'Pago de alcabalas y plusvalía'), ('16', 'Reingreso a la notaría para la revisión (3 días)'), ('17', 'Firmas de la compra y venta en notaria (2 dias)'), ('18', 'Registro de las escrituras en el municipio (3 dias )'), ('19', 'Fin Compra y venta de contado')], max_length=60, null=True),
        ),
    ]
