# Generated by Django 5.0.2 on 2024-02-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crea', '0025_alter_propiedad_disponible_proceso_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad_disponible',
            name='observaciones_procesos',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
